[package]
name = "anyval"
version = "0.1.0"
edition = "2024"

[dependencies]
count_tts = "0.2.0"
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }

[features]
serde = ["dep:serde"]
json = ["serde", "dep:serde_json"]
default = ["json", "serde"]
